# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
dataset: "AgamDao_23"
metadata: "config/metadata.tsv"
present_samples:  "resources/present.samples.txt"

# Directory of Illumina Miseq Run
illumina_dir: /home/sanj/projects/AmpSeq2023/resources/230203_M05658_0007_000000000-KPHPC

# Specify whether reference  provided is amplicon or wholegenome sequence data
reference_type: "wholegenome" # amplicon or wholegenome
# Genome fasta reference files
reference_name: 'AgamP4'
reference_fasta: /home/sanj/projects/AgamDao/AmpSeq2023/resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa
reference_gff3: /home/sanj/projects/AgamDao/AmpSeq2023/resources/reference/Anopheles-gambiae-PEST_BASEFEATURES_AgamP4.12.gff3

# .bed file of target SNPs
bed: "resources/AgamDao_wholegenome_snptargets.bed"

Coverage:
  activate: True
Stats:
  activate: True
Mapping:
  activate: True
