name: AmpSeeker-fastqmetadata

on: pull_request

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Set up python3
        uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Test workflow 
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache'
          stagein: 
            "
            cp -r docs/ .test/docs/ &&
            conda config --set channel_priority flexible
            "