name: AmpSeq

on: pull_request

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Test workflow 
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache'
          stagein: 
            "
            conda config --set channel_priority flexible
            cp -r docs/ .test/docs/
            "